# Generated by Django 4.2.11 on 2024-11-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('mileage', models.PositiveIntegerField()),
                ('engine_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetApp.serviceprovider')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetApp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('applicant_name', models.CharField(max_length=50)),
                ('applicant_contact', models.CharField(max_length=20)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('current_location', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=40)),
                ('time_of_allocation', models.DateTimeField()),
                ('request_status', models.CharField(choices=[('P', 'Pending'), ('O', 'Open'), ('C', 'Closed')], max_length=3)),
                ('mileage_at_assignment', models.IntegerField()),
                ('mileage_at_return', models.IntegerField()),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fleetApp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleetApp.vehicle')),
            ],
        ),
    ]
