# Generated by Django 4.2.11 on 2025-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_passports/'),
        ),
    ]
