# Generated by Django 4.2.11 on 2025-05-07 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Av', 'Available'), ('Allocated', 'Allocated')], default='Available', max_length=9),
        ),
    ]
