# Generated by Django 4.2.11 on 2025-05-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Saloon', 'Saloon Car'), ('SUV', 'SUV (Sport Utility Vehicle)'), ('Pickup', 'Pickup Truck'), ('Truck', 'Cargo Truck'), ('Motorcycle', 'Motorcycle'), ('Van', 'Van'), ('DoubleCab', 'Double Cabin')], max_length=20),
        ),
    ]
