# Generated by Django 4.2.11 on 2025-05-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Allocated', 'Allocated')], default='Available', max_length=9),
        ),
        migrations.CreateModel(
            name='GSMsensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('Speed', 'Speed'), ('Location', 'Location'), ('Fuel', 'Fuel Level'), ('Engine', 'Engine Temp')], max_length=20)),
                ('data_value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transmission_mode', models.CharField(choices=[('SMS', 'SMS'), ('GPRS', 'GPRS'), ('USSD', 'USSD'), ('Email', 'Email')], max_length=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetApp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('Low Fuel', 'Low Fuel'), ('Overspeed', 'Overspeeding'), ('High Temp', 'Engine Overheat')], max_length=50)),
                ('alert_message', models.TextField()),
                ('trigger_source', models.CharField(max_length=20)),
                ('priority_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('recipient_role', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetApp.gsmsensordata')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetApp.vehicle')),
            ],
        ),
    ]
