# Generated by Django 4.2.11 on 2024-11-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Av', 'Available'), ('Al', 'Allocated')], default='Available', max_length=2),
        ),
    ]
