# Generated by Django 4.2.11 on 2025-05-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0002_alter_vehicle_status_gsmsensordata_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='fleetApp.driver'),
        ),
    ]
