# Generated by Django 4.2.11 on 2025-05-17 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0002_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
