# Generated by Django 4.2.11 on 2024-11-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0002_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('GAS', 'Gasoline'), ('HYB', 'Hybrid'), ('DIS', 'Diesel'), ('ELE', 'Electric')], max_length=4),
        ),
    ]
