# Generated by Django 4.2.11 on 2025-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0003_alter_driver_passport_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='passport_photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
    ]
