# Generated by Django 4.2.11 on 2025-05-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0003_service_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='service_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feedback_notes', models.TextField(blank=True)),
                ('invoice_file', models.FileField(upload_to='invoices/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleetApp.service')),
            ],
        ),
    ]
