# Generated by Django 4.2.11 on 2025-05-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0003_alter_request_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
