# Generated by Django 4.2.11 on 2025-05-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0004_remove_driver_passport_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
    ]
