# Generated by Django 4.2.11 on 2024-11-24 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0004_delete_requisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=100)),
                ('time_of_allocation', models.DateTimeField(blank=True, null=True)),
                ('request_status', models.CharField(choices=[('P', 'Pending'), ('O', 'Open'), ('C', 'Closed')], default='P', max_length=1)),
                ('mileage_at_assignment', models.IntegerField(blank=True, null=True)),
                ('mileage_at_return', models.IntegerField(blank=True, null=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='fleetApp.requestor')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleetApp.vehicle')),
            ],
        ),
    ]
