# Generated by Django 4.2.11 on 2025-05-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0004_request_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_plate',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
