# Generated by Django 4.2.11 on 2025-05-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0005_driver_passport_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='passport_photo',
        ),
    ]
