# Generated by Django 4.2.11 on 2024-11-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetApp', '0006_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Av', 'Available'), ('Al', 'Allocated')], default='Available', max_length=2),
        ),
    ]
